# .pre-commit-config.yaml

repos:
  # Check for trailing whitespace, final newlines, etc.
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict

  - repo: https://github.com/streetsidesoftware/cspell-cli
    rev: v9.1.1 # Keep this version or update to the latest stable
    hooks:
      - id: cspell
        name: Check spelling in Markdown files
        args: ["--config", "cspell.json"]
        files: ^.*\.(md|qmd)$
      - id: cspell
        name: Check commit message spelling
        args:
          - --no-must-find-files
          - --no-progress
          - --no-summary
          - --files
          - .git/COMMIT_EDITMSG
        stages: [commit-msg]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        files: ^.*\.(md|qmd)$

  # Lint and format Python code blocks (if applicable)
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/tcort/markdown-link-check
    rev: v3.13.7
    hooks:
    - id: markdown-link-check
      args: [-q]
      files: ^.*\.(md|qmd)$

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0  # Use the latest stable version
    hooks:
      - id: detect-secrets
        name: Detect secrets within the codebase
        description: Detect and block secrets from committing to the codebase
